# Generated by Django 4.1.1 on 2022-10-01 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aluno",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="boletim",
            options={"ordering": ["-data_entrega"], "verbose_name_plural": "Boletins"},
        ),
        migrations.AlterModelOptions(
            name="disciplina",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="notasboletim",
            options={
                "ordering": ["-boletim"],
                "verbose_name_plural": "Notas dos Boletins",
            },
        ),
        migrations.AlterField(
            model_name="aluno",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="E-mail deve ser único",
                max_length=50,
                unique=True,
                verbose_name="e-mail",
            ),
        ),
        migrations.AlterField(
            model_name="boletim",
            name="aluno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.aluno"
            ),
        ),
        migrations.AlterField(
            model_name="notasboletim",
            name="disciplina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.disciplina"
            ),
        ),
    ]
